### ISSUE TITLE
Question about Section 4.2: Evaluation

### ISSUE THREAD

**Issue by jiunyen-ching** [yuxiaoguo/VVNet#2]
Hi, I have read your paper and found your implementations very interesting.
I am slightly confused about a sentence under Section 4.2 Evaluation - NYU & NYUCAD. 

> ... the small performance gap between our VVNetR models and SSCNET* on the NYU dataset is caused by the misalignment between the input and output.

Could you elaborate more about this?
Thank you.

**Comment by yuxiaoguo** [comment]
"The small performance gap" means the performance gap (**31.9 vs. 32.9**) in NYU & NYUCAD dataset is much closer than that (**59.1 vs 66.7**) in the SUNCG dataset.

In the NYU dataset, the reconstructed 3D semantic volume label isn't created from manual replaced by 3D objects rather than the original RGB-D images. Thus, there are many misalignments in the boundary, even some missing parts and directly replaced by boxes. In our experiments and observation, we believe these artificialities are hard to be fitted by the neural network, leading the gap smaller compared with SUNCG.

**Comment by jiunyen-ching** [comment]
Correct me if I'm wrong. My interpretation is if we follow the difference in performance between SSCNet* vs VVNetR-120,  we should also expect to see similar difference in scores between these two networks when tested on NYU & NYUCAD, right? But that is not the case for the reasons you gave above.

**Comment by yuxiaoguo** [comment]
Yes, we should hope an obvious difference in NYU & NYUCAD as shown in the SUNCG. However, the final results show that we only have a small improvement (**1%**). 

To interpret it, we believe this is because of the misalignments in NYU & NYUCAD datasets. Since even we did a good job in alignment parts, the overall performance will be influenced by these misalignment parts. This may be the reason for only a small gap observed in NYU & NYUCAD datasets.

**Comment by jiunyen-ching** [comment]
I see. It is very clear to me now. Thank you very much for your clarification.
